### PR TITLE
fix(i18n): add missing theme options i18n

### PR DESCRIPTION
**Pull request by m01i0ng**
### PR Checklist

If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/master/.github/CONTRIBUTING.md)

#### What is the current behavior?

image

#### What is the new behavior?

image

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Specific Instructions

Are there any specific instructions or things that should be known prior to review?

### CODE REVIEW

**Comment by ysfscream** [comment]
Thanks again! It's good! The other two are missing, but I only see the translation of night?

Suggestion.

Light -> 明亮
dark -> 暗黑
night -> 夜间

**Comment by ysfscream** [comment]
And sorry about the last comment! I forgot to translate it before, but could you please update the translation according to the suggestion? Thanks.

**Comment by m01i0ng** [comment]
> And sorry about the last comment! I forgot to translate it before, but could you please update the translation according to the suggestion? Thanks.

Haha, sure. I will update the pr.

**Comment by m01i0ng** [comment]
@ysfscream Updated with the exists pr.

**Comment by ysfscream** [comment]
@m01i0ng Thank you very much! I'll merge later.

**Review by ysfscream — APPROVED** [review]

**Pull request merged**
