### PR TITLE
chore(deps) Bump various dependency versions

### PR DESCRIPTION
**Pull request by sconvent**
### PR Checklist

If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md)

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Summary
This PR will bump various dependencies to the newest version without switching to a new major version.

### CODE REVIEW

**Comment by ysfscream** [comment]
Hi, @sconvent. Thanks for your kind help, but currently, the CI is failing, and we need to build our application correctly. Please check before submitting.

**Comment by sconvent** [comment]
Hi @ysfscream. Sorry, my mistake. Should be fixed now.

**Comment by ysfscream** [comment]
@sconvent OK, thanks. Waiting for our test locally.

**Comment by Red-Asuka** [comment]
Hi, @sconvent. I run the command `yarn electron:serve` trying to start the development environment locally, but it was not successful.

image

**Comment by ysfscream** [comment]
@sconvent Hi, thanks for your PR, but we can not run it locally, so I will close this issue temperature.

**Pull request closed without merging**
