### PR TITLE
improve(desktop): improve experience with avro

### PR DESCRIPTION
**Pull request by LAST7**
#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Specific Instructions

Are there any specific instructions or things that should be known prior to review?

### CODE REVIEW

**Comment by LAST7** [comment]
Something weird happens when importing 'xxx.json' file as avro schema. Though the filename readed from the file system ends with '.json', but after it's journey to the database, a '.avsc' is added to the end of the filename: renaming it to 'xxx.json.avsc'.

Howerver, since the filtering logic of selecting imported schema is by examining their extensions, this strange 'xxx.json.avsc' name surprisingly does not require any further processing to be listed in the options in the schema tab.

That being said, I still hope the reason of this strange process to be found.

**Review by ysfscream — APPROVED** [review]

**Comment by ysfscream** [comment]
> Something weird happens when importing 'xxx.json' file as avro schema. Though the filename readed from the file system ends with '.json', a '.avsc' is added to the end of the filename: renaming it to 'xxx.json.avsc' after it's journey to the database.

I will test locally to find the issue. Thanks for your report.

**Comment by ysfscream** [comment]
@LAST7, in this PR https://github.com/emqx/MQTTX/pull/1764, I fixed the issue of file extensions. This isn't a strange problem. In the code, every import automatically adds a suffix.

However, there needs to be a solution with logical judgment. So, I made a quick fix. Briefly speaking, it checks if the file extension is correct. If it's incorrect, it deletes it and adds the expected suffix. Although the `.json` suffix is legal in Avro, I still automatically added or retained the `.avsc` suffix format to be more in line with the specification. I hope this can help you. Thanks!

**Comment by LAST7** [comment]
> @LAST7, in this PR #1764, I fixed the issue of file extensions. This isn't a strange problem. In the code, every import automatically adds a suffix.
> 
> However, there needs to be a solution with logical judgment. So, I made a quick fix. Briefly speaking, it checks if the file extension is correct. If it's incorrect, it deletes it and adds the expected suffix. Although the `.json` suffix is legal in Avro, I still automatically added or retained the `.avsc` suffix format to be more in line with the specification. I hope this can help you. Thanks!

Ah, I see the reason now. THX!

**Pull request merged**
