### PR TITLE
 feat(desktop): support install mqttx cli one click

### PR DESCRIPTION
**Pull request by ysfscream**
### PR Checklist

If you have any questions, you can refer to the [Contributing Guide](https://github.com/emqx/MQTTX/blob/main/.github/CONTRIBUTING.md)

#### What is the current behavior?

The desktop version and the CLI version installations are relatively independent, and users need to download them separately in different scenarios.

#### Issue Number

Example: None

#### What is the new behavior?

After downloading the desktop version, allow users to directly install MQTTX CLI with one click if needed.

image

image

image

image

image

image

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Specific Instructions

Are there any specific instructions or things that should be known prior to review?

### CODE REVIEW

**Comment by Red-Asuka** [comment]
@ysfscream I see that the https://github.com/jorangreef/sudo-prompt project has been archived. Is there a more suitable library that is still being maintained?

**Review by Red-Asuka — APPROVED** [review]

**Review by XL-YiBai — APPROVED** [review]

**Comment by Red-Asuka** [comment]
@ysfscream I noticed that it needs to be done manually on Windows, but it can be achieved by configuring system environment variables. You can refer to https://stackoverflow.com/questions/59560042/how-to-append-values-to-the-path-environment-variable-in-nodejs.

**Comment by ysfscream** [comment]
> @ysfscream I see that the [jorangreef/sudo-prompt](https://github.com/jorangreef/sudo-prompt) project has been archived. Is there a more suitable library that is still being maintained?

I am still looking for a suitable replacement. Although the current project has been archived, it is still functional and stable, with 2 million weekly downloads on NPM. Please let me know if you have a suitable alternative in mind.

**Comment by ysfscream** [comment]
> @ysfscream I noticed that it needs to be done manually on Windows, but it can be achieved by configuring system environment variables. You can refer to [stackoverflow.com/questions/59560042/how-to-append-values-to-the-path-environment-variable-in-nodejs](https://stackoverflow.com/questions/59560042/how-to-append-values-to-the-path-environment-variable-in-nodejs).

Thank you for the suggestion! This looks very useful. I'll try implementing this in the next PR.

**Pull request merged**
