### PR TITLE
feat(decoder): added CBOR as new option data type to decode the paylo…

### PR DESCRIPTION
**Pull request by Danfx**
Added CBOR as new option data type to decode the payload of MQTT messages. The new option was added as below:
Screenshot from 2024-01-03 15-49-47

### CODE REVIEW

**Comment by ysfscream** [comment]
Hey @Danfx 

Thanks a ton for adding this feature! I've got to admit I'm unfamiliar with CBOR, so I'd appreciate any resources or a quick rundown to get me up to speed. Also, it would be awesome if you could show me a working example or test case for this new feature – I'm eager to see how it works and understand its benefits.

Big thanks to you and all the community contributors for your hard work – it's what makes this project thrive. Looking forward to learning more and diving into this!

Cheers! 🍻

**Comment by Danfx** [comment]
Hi @ysfscream 
Thanks to appreciate this feature. I've see that MQTTx is a great tool that helps the community to troubleshoot the MQTT messages. Thanks to start this project.

CBOR is a otimized data type more than JSON because you use less data to represents same information and helps IoT devices to gain more performance and use less network that implies on battery lifetime.

To learn more advantages about CBOR, please see the links:
- CBOR is Greener than JSON
https://raw.githubusercontent.com/intarchboard/e-impact-workshop-public/main/papers/Moran-Birkholz-Bormann_Sustainability-considerations-for-networking-equipment.pdf.pdf

- Official Site: 
https://cbor.io/

- CBOR Playground:
https://cbor.me/

Cheers!!!

**Comment by ysfscream** [comment]
Thank you so much for your contribution and the detailed explanation. I apologize for only now getting to this PR. Your addition of the CBOR decoding feature will be released in the next version. I will do some local testing, and if there are any issues, I will discuss them with you in this PR thread. If possible, we can also consider adding a CBOR encoding method on the publishing side.

Thanks again for your support of the project!

**Review by Red-Asuka — APPROVED** [review]

**Comment by Red-Asuka** [comment]
@Danfx Thank you very much for your contribution!

**Comment by ysfscream** [comment]
@Danfx The current release also supports CBOR encoding, so you can use MQTTX to send CBOR messages. After the PR #1563 merge, you can update and test the latest code.

**Comment by Danfx** [comment]
> Thank you so much for your contribution and the detailed explanation. I apologize for only now getting to this PR. Your addition of the CBOR decoding feature will be released in the next version. I will do some local testing, and if there are any issues, I will discuss them with you in this PR thread. If possible, we can also consider adding a CBOR encoding method on the publishing side.
> 
> Thanks again for your support of the project!

Right! No problem. I will make the publishing side.

**Pull request merged**
